import{c as o}from"./_plugin-vue_export-helper-Cm6_9V8g.js";const n={async getConsultations(){try{return(await o.get("/consultations")).data}catch(t){throw console.error("Erreur lors de la récupération des consultations :",t),t}},async getConsultation(t){try{return(await o.get(`/consultations/${t}`)).data}catch(r){throw console.error(`Erreur lors de la récupération de la consultation avec l'id ${t} :`,r),r}},async createConsultation(t){try{return(await o.post("/consultations",t)).data}catch(r){throw console.error("Erreur lors de la création de la consultation :",r),r}},async updateConsultation(t,r){try{return(await o.put(`/consultations/${t}`,r)).data}catch(e){throw console.error(`Erreur lors de la mise à jour de la consultation avec l'id ${t} :`,e),e}},async deleteConsultation(t){try{return(await o.delete(`/consultations/${t}`)).data}catch(r){throw console.error(`Erreur lors de la suppression de la consultation avec l'id ${t} :`,r),r}},async getConsultationsByPatiente(t){try{return(await o.get(`/consultations/patient/${t}`)).data}catch(r){throw console.error("Erreur lors de la récupération des consultations :",r),r}},async getRendezVousByPatiente(t){try{return(await o.get(`/patients/${t}/rendezvous`)).data}catch(r){throw console.error("Erreur lors de la récupération des rendez-vous :",r),r}}};export{n as c};
